### ISSUE TITLE
Facebook to Let Users Rank Credibility of News

### ISSUE THREAD

**Issue by allenleein** [allenleein/brains#129]
<img src="https://static01.nyt.com/images/2018/01/20/business/20facebook1/merlin_131864402_63961789-819a-40c9-9f71-0aa091704790-master768.jpg"><b>Facebook to Let Users Rank Credibility of News</b><br>
SAN FRANCISCO &mdash; Facebook said on Friday that it planned to prioritize high-quality news on the social network by allowing its users to rank news sources that they see as the most credible and trustworthy.<br>
<br>
Tags:<br>
<br>
via Pocket http://ift.tt/2Du2GBF<br>
<br>
January 20, 2018 at 10:10AM

**Comment by kevinphys** [comment]
和我三年前和你討論過的 google extension 想法一樣啊！
