### ISSUE TITLE
 Hedging from Broken Capitalism and Unstable World

### ISSUE THREAD

**Issue by allenleein** [allenleein/brains#2134]
- [ ] **Chp.1 Broken Capitalism and Unstable World**
    - Broken and Unstable World #2759 
    - The Liquid Advantage in Our Era #2851

- [ ] **Chp.2 The Big Escape**
    - Cryptocurrency offers a decentralized protection from centralized corruption.
    - Bitcoin is hedge against politics. 
    - The Escape from Broken Capitalism #2850

- [ ] **Chp.3 The Shift of Decentralization**
    - Liquidity and eSports

**Comment by functionalflow** [comment]
Cryptocurrency offers a decentralized protection from centralized corruption.

Bitcoin is hedge against politics.
